### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by wrh2** [oresat/system-controller#1]
Repository is in need of a description. I'd gladly give it one myself but I don't have the ability to do that for whatever reason.

**Comment by ThirteenFish** [comment]
I've got the ability to put it in. If you write the text I'll get it up there.

**Comment by wrh2** [comment]
Something like: "Radiation-hardened avionics module for CubeSat v1. Responsible for monitoring the well-being of the stack and power cycling modules when Single-Event Upsets happen."

**Comment by natronics** [comment]
I added it. Has to be really short to fit in the header though. I only took the first sentence. Is that look okay?

**Comment by wrh2** [comment]
Looks good. Thanks, Nate.
