### ISSUE TITLE
images for Readme

### ISSUE THREAD

**Issue by shanodean** [oresat/system-controller#4]
<img width="1564" alt="system overview with sc" src="https://cloud.githubusercontent.com/assets/14911274/15880573/b1dd139c-2ce3-11e6-835e-d4301859c13e.png">

**Comment by shanodean** [comment]
<img width="514" alt="screen shot 2016-06-07 at 7 18 18 pm" src="https://cloud.githubusercontent.com/assets/14911274/15880699/a9ea9262-2ce4-11e6-8fe5-72985635abf4.png">

**Comment by shanodean** [comment]
<img width="288" alt="screen shot 2016-06-07 at 7 18 18 pm" src="https://cloud.githubusercontent.com/assets/14911274/15880855/0a21da22-2ce6-11e6-9eb7-03c3dbf73aa6.png">

**Comment by shanodean** [comment]
<img width="216" alt="screen shot 2016-06-07 at 7 18 18 pm" src="https://cloud.githubusercontent.com/assets/14911274/15882215/706dbe6c-2cf1-11e6-8078-aa307ecb59ea.png">

**Comment by shanodean** [comment]
![sc_board_photo](https://cloud.githubusercontent.com/assets/14911274/15908719/e8b2d44e-2d77-11e6-9805-5ce5d18c3334.png)

**Comment by shanodean** [comment]
![sc_board_photo copy](https://cloud.githubusercontent.com/assets/14911274/15908761/28c9cc18-2d78-11e6-9def-4ee5a718bb30.png)

**Comment by shanodean** [comment]
![sc_board_photo copy](https://cloud.githubusercontent.com/assets/14911274/15908833/86da389c-2d78-11e6-990a-24c96bd0aba1.png)

**Comment by heathjake** [comment]
This is done
